modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/AweiMC/Systrace/issues"
license = "GNU AGPLv3"

[[mods]]
modId = "systrace"
version = "${version}"
displayName = "Systrace"
authors = "AweiMC"
description = '''
A diagnostic tool that exports system, thread, mixin and JFR profiling data.
'''
logoFile = "assets/systrace/icon.png"

[[dependencies.systrace]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.systrace]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "systrace.mixins.json"
